### ISSUE TITLE
The FR cobots URDF files

### ISSUE THREAD

**Issue by rgruberski** [FAIR-INNOVATION/frcobot_ros2#2]
Hi! Do you have URDF files for your robots or CAD models to prepare the URDF files myself? I have FR5 in my lab and would like to use it with ROS2 by MoveIt2. Thank you for any support and suggestions.

**Comment by FAIR-INNOVATION** [comment]
Hi, Robert Gruberski! Thanks for your issue. 

- We recommend that you contact the local supplier where you purchased the cobot for faster and more appropriate technical support.
- If you can't contact your supplier, Before providing support, we need to confirm some information, including the current version of the FR5 cobot you own. Can you send the cobot information label and some photos of the FR cobot's appearance? It's usually on the upperarm link of the FR5 cobot. 

Best regards!

**Comment by rgruberski** [comment]
Hi! Thanks for your quick response. I can't contact the local supplier, because I bought the robot directly from China in Shenzhen. I bought it from a local trader and can't get their technical support. So, I would like to talk with you directly.

**Comment by rgruberski** [comment]
Hi! Thanks for your quick response. I can't contact the local supplier, because I bought the robot directly from China in Shenzhen. I bought it from a local trader and can't get their technical support. So, I would like to talk with you directly.

Please check the pictures that I attached. I hope it will be enough to get your support.

BTW. Is it possible to use the urdf files from the ROS1 version? Is it hardware-compatible? I can port it myself for Moveit2 if you don't have a ready-to-use package. If you have, please share, it will be much faster and easier to use something ready.

Thank you for your support!

![IMG_9149](https://github.com/FAIR-INNOVATION/frcobot_ros2/assets/4487397/4245575c-ff4d-4022-b7a1-4d595b762cba)
![IMG_9150](https://github.com/FAIR-INNOVATION/frcobot_ros2/assets/4487397/35052445-e67d-44fa-a447-0a773f6e38cd)
![IMG_9152](https://github.com/FAIR-INNOVATION/frcobot_ros2/assets/4487397/ed25f1c0-1597-45ba-8551-a6938d1843e9)

**Comment by FAIR-INNOVATION** [comment]
Hi! Thanks for your pics.
This is our FR5-V6.0 ROS package, We hope you to check and enjoy it.
Happy New Year!!!
[FR5-V6.0-20231229.zip](https://github.com/FAIR-INNOVATION/frcobot_ros2/files/13792366/FR5-V6.0-20231229.zip)

**Comment by FAIR-INNOVATION** [comment]
Hi! Thanks for your pics.
This is our FR5-V6.0 ROS package, We hope you will check and enjoy it
Happy New Year!!!
[FR5-V6.0-20231229.zip](https://github.com/FAIR-INNOVATION/frcobot_ros2/files/13792378/FR5-V6.0-20231229.zip)

**Comment by rgruberski** [comment]
Thank you! I will check it. The issue can be closed at this moment.

**Comment by chipper10** [comment]
> Hi! Thanks for your pics. This is our FR5-V6.0 ROS package, We hope you will check and enjoy it Happy New Year!!! [FR5-V6.0-20231229.zip](https://github.com/FAIR-INNOVATION/frcobot_ros2/files/13792378/FR5-V6.0-20231229.zip)

Thank you very much! Do you also have a ROS2 URDF package?
